name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Get Go environment
        id: go-env
        shell: bash
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            test-

      - name: Run tests
        env:
          GOARCH: ${{ matrix.arch }}
          GOFLAGS: ${{ matrix.flags }}
        run: go test --timeout 15m ./...
