name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      # Notice: we're using read-only cache.
      #
      # See https://github.com/actions/setup-go/issues/357#issuecomment-1486486358
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m
          # Package/build cache already provided above.
          #
          # Disable module cache.
          skip-pkg-cache: true
          # Disable build cache.
          skip-build-cache: true

  # Check if there are any dirty changes after go mod tidy
  check-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      # Notice: we're using read-only cache.
      #
      # See https://github.com/actions/setup-go/issues/357#issuecomment-1486486358
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Check git diff
        run: git diff --exit-code

