name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write
  id-token: write # needed for signing the images with GitHub OIDC Token **not production ready**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE: ghcr.io/${{ github.repository }}
  DOCKER_CLI_EXPERIMENTAL: "enabled"

  # https://go.dev/dl/
  #
  # latest stable version
  GOVERSION: 1.20.2
  # SHA256 Checksum for "Source" Kind file
  GOSHA256: 4d0e2850d197b4ddad3bdb0196300179d095bb3aefd4dfbc3b36702c3728f8ab

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: List keys
        run: gpg -K

      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache: false

      - name: Go env
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: go-release-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-release-

      - uses: actions/cache@v3
        name: Bootstrap cache
        with:
          path: _out/go-linux-riscv64-bootstrap.tbz
          key: go-bootstrap

      - name: Setup
        run: ./bootstrap.sh

      - name: Build
        run: ./build.sh

      - name: Pack
        run: ./pack.sh

      - name: Checksums
        run: ./checksums.sh

      - name: Sign
        run: ./sign.sh

      - name: Release notes
        run: go run ./cmd/release > _out/release.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: _out/release.md
          files: |
            _out/go-linux-riscv64-bootstrap.tbz
            _out/go-linux-riscv64-bootstrap.tbz.asc
            _out/checksums.sha256.txt
            _out/checksums.sha256.txt.asc
            _out/go${{ env.GOVERSION }}.linux-riscv64.tar.gz
            _out/go${{ env.GOVERSION }}.linux-riscv64.tar.gz.asc
            _out/go${{ env.GOVERSION }}.src.tar.gz
